language: scala
sudo: false
cache:
  directories:
    - $HOME/.ivy2
matrix:
  include:
    # Scala 2.11
    - jdk: openjdk7
      scala: 2.11.7
      env: TEST_SPARK_VERSION="2.0.0"
    - jdk: openjdk7
      scala: 2.11.7
      env: TEST_SPARK_VERSION="2.0.1"
    - jdk: openjdk7
      scala: 2.11.7
      env: TEST_SPARK_VERSION="2.1.0"
    # Scala 2.10
    - jdk: openjdk7
      scala: 2.10.4
      env: TEST_SPARK_VERSION="2.0.1"
    - jdk: openjdk7
      scala: 2.10.4
      env: TEST_SPARK_VERSION="2.1.0"
script:
  - sbt ++$TRAVIS_SCALA_VERSION scalastyle
  - sbt ++$TRAVIS_SCALA_VERSION "test:scalastyle"
  - sbt -Dspark.testVersion=$TEST_SPARK_VERSION ++$TRAVIS_SCALA_VERSION coverage test
  - sbt ++$TRAVIS_SCALA_VERSION assembly
after_success:
  - bash <(curl -s https://codecov.io/bash)
